package com.trustai.common_base.exceptions;

public interface ErrorCode {
    // Investment
    String INSUFFICIENT_BALANCE = "INV001";
    String INVALID_RANK_CONFIG  = "INV002";
    String MIN_INVESTMENT_NOT_MET = "INV003";
    //String AMOUNT_BELOW_MIN_RANK_THRESHOLD = "";
    //String INSUFFICIENT_INVESTMENT_FOR_RANK = "";
    //String INVESTMENT_BELOW_RANK_REQUIREMENT = "";
    //String INVALID_INVESTMENT_AMOUNT_FOR_RANK = "";
    String USER_RANK_NOT_IN_PARTICIPATION_LEVELS = "INV004";
    //String INELIGIBLE_USER_RANK_FOR_SCHEMA = "";
    //String RANK_NOT_ALLOWED_FOR_SCHEMA = "";

    String USER_RANK_MISMATCH_LINKED_RANK = "INV005";
    //String INVALID_USER_RANK_FOR_LINKED_SCHEMA = "";
    //String SCHEMA_LINKED_RANK_MISMATCH = "";
    //String RANK_CODE_NOT_EQUAL_TO_LINKED_RANK = "";

    // Reservation
    String STAKE_ALREADY_RESERVED = "RSV001";              // 1
    String STAKE_SCHEMA_NOT_FOUND = "RSV002";              // 2
    String INSUFFICIENT_WALLET_BALANCE = "RSV003";         // 3
    String RESERVATION_NOT_FOUND_OR_SOLD = "RSV004";       // 4
    String WALLET_DEDUCTION_FAILED = "RSV005";             // 5

    String FIXED_AMOUNT_MISMATCH = "INV006"; // INVALID_FIXED_INVESTMENT_AMOUNT, AMOUNT_NOT_EQUAL_TO_FIXED_MINIMUM
    String INVESTMENT_AMOUNT_OUT_OF_RANGE  = "INV007"; // AMOUNT_NOT_IN_ALLOWED_RANGE, INVALID_RANGE_INVESTMENT_AMOUNT
    String UNKNOWN_SCHEMA_TYPE   = "INV008"; // UNSUPPORTED_SCHEMA_TYPE, INVALID_SCHEMA_TYPE



    String REST_CALL_EXCEPTION = "EXT001";



}
